%% c2a_second_level_regression.m
%
%
% *USAGE*
%
% This script displays second-level (i.e. across subjects) regression
% results generated by prep_3a_run_second_level_regression_and_save.m
%
% Run this script with Matlab's publish function to generate html report of results:
% publish('c2a_second_level_regression','outputDir',htmlsavedir)
% 
% See the documentation of prep_3a_run_second_level_regression_and_save.m
% for more info and options
%
%
% *OPTIONS FOR CURRENT SCRIPT*
% 
%   NOTE: 
%       defaults are specified in a2_set_default_options for any given model,
%       but if you want to run the same model with different options, 
%       you can make a copy of this script with a letter index (e.g. _s6a_) 
%       and change the default option below
%
% _GLM options_
%
% * save_figures_glm                true saves .svg files of all figures generated by c2a_second_level_regression.m (slow, takes up space)
%
% * q_threshold_glm                 threshold for FDR-corrected display items
%
% * p_threshold_glm                 threshold for uncorrected display items
%
% * k_threshold_glm                 extent threshold for both corrected and uncorrected display items
%
% * BF_threshold_glm                threshold for Bayes Factor maps, |BF| > 10 indicates strong evidence in favour of H1 (positive value) or H0 (negative value) - see help.statistic_image.estimateBayesFactor for details
%
%
% _MVPA options_
%
% * dobootstrap_mvpa_reg_cov
%
%     mvpa bootstrapping options
%
%       * boot_n_mvpa_reg_cov           number of bootstrap samples
%
%       * parallelstr_mvpa_reg_cov      'parallel'/'noparallel'  
%
%       * cons2boot_mvpa_reg_cov        vector of indices of conditions/contrasts to bootstrap
%
%     mvpa thresholding options
%
%       * q_threshold_mvpa_reg_cov      threshold for fdr-corrected maps
%
%       * k_threshold_mvpa_reg_cov      extent threshold (in voxels)
%
%
% *OPTIONS TO COPY FROM CORRESPONDING PREP_3a_ SCRIPT*
%
% _Mandatory options_
%
% * mygroupfieldname                    'contrasts'/'conditions'
%
% * results_suffix                      name added to results file by prep_3a script in case of multiple versions of model, e.g. 'covariate_rating'
%
%
% _Options to copy if specified in prep_3a script_
%
% * covs2use                            cell array of covariate used
%
% * group_id                            group variable name
%
%
% _Custom options from prep_3a script_
% 
% see first section of this script below for overview
%
% -------------------------------------------------------------------------
%
% revamped by: Lukas Van Oudenhove
%
% date:   Dartmouth, May, 2022
%
% -------------------------------------------------------------------------
%
% c2a_second_level_regression.m         v8.4
%
% last modified: 2026/08/14
%
%
%% GET AND SET OPTIONS
% -------------------------------------------------------------------------

% GET MODEL-SPECIFIC PATHS AND OPTIONS

a_set_up_paths_always_run_first;

% NOTES 
%   1. CHANGE THIS TO THE MODEL-SPECIFIC VERSION OF THIS SCRIPT
%   2. THIS WILL ALSO AUTOMATICALLY CALL A2_SET_DEFAULT_OPTIONS


% COPY OPTIONS FROM CORRESPONDING PREP_3a_ SCRIPT

% Mandatory options from prep_3a script

mygroupnamefield = 'contrasts'; 
results_suffix = ''; % suffix of your choice added to .mat file with saved results

% Options to copy if specified in prep_3a script

% covs2use = {'varname1'};
% group_id = {'varname2'};

% Custom options from prep_3a script

% dorobust = true/false;
% dorobfit_parcelwise = true/false;
%   csf_wm_covs = true/false;
%   remove_outliers = true/false;
% atlasname_glm = 'atlas_name';
% atlas_granularity = 1/2/3;
% maskname_glm = 'mask_name';
% myscaling_glm = 'raw'/'scaled'/'scaled_contrasts';
% design_matrix_type = 'custom'/'group'/'onesample';
% doBayes = true/false;
% doTFCE = true/false;
%     perm_n_tfce = 1000;                                                    
%     tfce_sidedness = 'two';                                                
%     tfce_tail = 'pos/neg';  
%     tfce_correction = 'fwe'/'fdr';                                         
%         which multiple-comparisons correction to report for TFCE. 'fwe'
%         (default) uses the max-statistic FWE p-values (Smith & Nichols
%         2009) returned in tfce_info.p_FWE by group_tfce_from_subject_maps;
%         'fdr' uses FDR on the uncorrected permutation p-values, the old
%         behaviour. Both thresholded maps are saved either way - only the
%         reported one gets montages and region tables, since labelling
%         regions against an atlas is by far the slowest step here.
%         TFCE results generated before p_FWE was implemented carry no
%         p_FWE field and fall back to 'fdr' with a warning.
%     p_threshold_fwe = .05;                                                 
%         threshold for the FWE-corrected TFCE p-values. These are already
%         corrected, so they are thresholded uncorrected at this value -
%         applying FDR on top would correct twice.
% domvpa_reg_cov = true/false;
%   algorithm_mvpa_reg_cov = 'cv_pcr'/'cv_pls'/etc;
%   holdout_set_method_mvpa_reg_cov = 'no_group'/'group';
%   nfolds_mvpa_reg_cov = x;
%   zscore_outcome_mvpa_reg_cov = true/false;

% SET CUSTOM OPTIONS FOR CURRENT SCRIPT

% NOTE 
%   only specify if you want to run a second version of your model with different options
%   than the defaults you set in your model-specific version of a2_set_default_options.m
%   EXCEPTION: cons2boot_mvpa_reg_cov, which is not in the a2 script, but can be used here
%       if you do not want to bootstrap all contrasts

% GLM options

% save_figures_glm = true/false;
% q_threshold_glm = .x;
% p_threshold_glm = .yyy;
% k_threshold_glm = zz;
% BF_threshold_glm = x;

% MVPA options

% dobootstrap_mvpa_reg_cov = true/false;
    % mvpa bootstrapping options
%     boot_n_mvpa_reg_cov = x;                                      
%     parallelstr_mvpa_reg_cov = 'parallel'/'noparallel'; 
%     cons2boot_mvpa_reg_cov = [y1,y2,...];
    % mvpa thresholding options
%     q_threshold_mvpa_reg_cov = .yy;                                  
%     k_threshold_mvpa_reg_cov = z; 

% GET SCALING OPTION

switch myscaling_glm

    case 'raw'
        fprintf('\ncontrast calculated on raw (unscaled) condition images used in second-level GLM\n\n');
        scaling_string = 'no_scaling';

    case 'scaled'
        fprintf('\ncontrast calculated on z-scored condition images used in second-level GLM\n\n');
        scaling_string = 'scaling_z_score_conditions';

    case 'scaled_contrasts'
        fprintf('\nl2norm scaled contrast images used in second-level GLM\n\n');
        scaling_string = 'scaling_l2norm_contrasts';

    otherwise
        error('\ninvalid option "%s" defined in myscaling_glm variable in a2_set_default_options script, choose between "raw", "scaled", or "scaled_contrast" given option "%s" defined in mygroupnamefield variable\n', myscaling_glm, mygroupnamefield);

end


% GET MASKING OPTION

% NOTE: In case of parcelwise regression, masking is already done in prep_3a script as part of robfit_parcelwise, but we need the atlas object and define mask_string var

if ~dorobfit_parcelwise

    if exist('maskname_glm', 'var') && ~isempty(maskname_glm) && exist(maskname_glm, 'file')
        
        apply_mask_before_fdr = true;
        
        [~,maskname_short] = fileparts(maskname_glm);
            if contains(maskname_short,'nii')
                [~,maskname_short] = fileparts(maskname_short);
            end
            
        mask_string = sprintf('masked with %s', maskname_short);
        
        glmmask = fmri_mask_image(maskname_glm, 'noverbose'); 
            if any(unique(glmmask.dat) ~= 1)
                glmmask.dat(glmmask.dat > 0) = 1; % binarize mask if needed
            end
            
        fprintf('\nMasking voxelwise results visualization with %s\n\n', maskname_short);
        
        % MONTAGE OF MASK
        
        % canlab_results_fmridisplay's 'compact' layout only calls axes('Position',...);
        % unlike 'multirow' it never opens a figure of its own, so it draws into whatever
        % figure is current - the previous block's montage, or the last figure left open by
        % the previous script in the same session. Open a fresh one. ('multirow' does
        % create its own figure, so those call sites are deliberately left alone: adding
        % figure; there would leave an empty figure behind for every montage.)
        figure;
        o2 = canlab_results_fmridisplay([], 'compact');
        o2 = addblobs(o2, glmmask,'onecolor','color',[0.4 0.2 0.6],'trans','transvalue',0.50);
        o2 = title_montage(o2, 5, ['voxel-wise analysis masked with: ' maskname_short]);
        plugin_set_figure_size;
        drawnow,snapnow;
        
        clear o2
        
    else
        
        apply_mask_before_fdr = false;
        mask_string = sprintf('without masking');
        fprintf('\nShowing voxelwise results without masking\n\n');
        
    end 

end

if exist('atlasname_glm','var') && ~isempty(atlasname_glm)

    if contains(atlasname_glm,'.mat')
        
        load(atlasname_glm);
        [~,atlasname_short] = fileparts(atlasname_glm);
        clear mask
        
        if logical(exist('atlas_granularity','var')) && atlas_granularity ~= 1
            combined_atlas = combined_atlas.downsample_parcellation(['labels_' num2str(atlas_granularity)]);
        end
        
        if dorobfit_parcelwise
            
            maskname_short = atlasname_short;
            mask_string = sprintf('masked with %s', maskname_short);
            fprintf('\nRunning parcelwise analysis in custom-made atlas %s at granularity level labels_%d\n\n', atlasname_short, atlas_granularity);
            
        end
        
        fprintf('\nLabeling regions using custom-made atlas %s at granularity level labels_%d\n\n', atlasname_short, atlas_granularity);
        
        % MONTAGE OF ATLAS
        
        cmap = colormap('colorcube');
        close gcf;
        
        figure;
        o2 = canlab_results_fmridisplay([], 'compact');
        o2 = addblobs(o2, atlas2region(combined_atlas),'indexmap',cmap,'interp','nearest');
        if dorobfit_parcelwise
            o2 = title_montage(o2, 5, ['parcel-wise analysis in atlas: ' atlasname_short ' at granularity level labels_' num2str(atlas_granularity)]);
        else
            o2 = title_montage(o2, 5, ['voxel-wise analysis labeled with atlas: ' atlasname_short ' at granularity level labels_' num2str(atlas_granularity)]);
        end
        plugin_set_figure_size;
        drawnow,snapnow;
        
        clear o2

    elseif ischar(atlasname_glm)

        combined_atlas = load_atlas(atlasname_glm);
        
        if logical(exist('atlas_granularity','var')) && atlas_granularity ~= 1
            combined_atlas = combined_atlas.downsample_parcellation(['labels_' num2str(atlas_granularity)]);
        end
        
        if contains(atlasname_glm,'canlab2023') || contains(atlasname_glm,'canlab2024')
            combined_atlas = combined_atlas.threshold(0.20); % only keep probability values > 0.20 in probabistic canlab2023 atlas
        end
        
        if dorobfit_parcelwise
            mask_string = sprintf('in atlas %s',atlasname_glm);
            
            fprintf('\nRunning parcelwise analysis in custom-made atlas %s at granularity level labels_%d\n\n', atlasname_glm, atlas_granularity);
            
        end
        
        fprintf('\nLabeling regions using custom-made atlas %s at granularity level labels_%d\n\n', atlasname_glm, atlas_granularity);
        
        % MONTAGE OF ATLAS
        
        cmap = colormap('colorcube');
        close gcf;
        
        figure;
        o2 = canlab_results_fmridisplay([], 'compact');
        o2 = addblobs(o2, atlas2region(combined_atlas),'indexmap',cmap,'interp','nearest');
        if dorobfit_parcelwise
            o2 = title_montage(o2, 5, ['parcel-wise analysis in atlas: ' atlasname_glm ' at granularity level labels_' num2str(atlas_granularity)]);
        else
            o2 = title_montage(o2, 5, ['voxel-wise analysis labeled with atlas: ' atlasname_glm ' at granularity level labels_' num2str(atlas_granularity)]);
        end
        plugin_set_figure_size;
        drawnow,snapnow;
        
        clear o2

    else

         error('\ninvalid option "%s" defined in atlasname_glm variable, should be a keyword for load_atlas.m or a .mat file containing an atlas object, check docs"\n\n',atlasname_glm)

    end

else

    if dorobfit_parcelwise
        mask_string = sprintf('without masking');
        
        fprintf('\nShowing parcelwise results without masking in 489 parcels of canlab_2018 atlas\n\n');
        
    end

end


% LOAD BRAINMASK

brainmask = fmri_mask_image(maskname_brain,'noverbose');


% CHECK Q THRESHOLD IN CASE OF PARCELWISE ANALYSIS

if dorobfit_parcelwise
    
    if q_threshold_glm ~= 0.05
        fprintf('\n');
        warning('Parcelwise analysis only implemented with qFDR < 0.05, will default to this threshold')
        fprintf('\n');
    end
    
end


%% LOAD RESULTS IF NEEDED
% -------------------------------------------------------------------------

%%
% *GLM*

if ~dorobfit_parcelwise
    
    resultsvarname = 'regression_stats_results';
    resultsstring = 'regression_stats_and_maps_';
    analysis_type = 'voxel-wise';
    
else
    
    resultsvarname = 'parcelwise_stats_results';
    resultsstring = 'parcelwise_stats_and_maps_';
    analysis_type = 'parcel-wise';
    
end

if ~exist(resultsvarname, 'var')
    
    fprintf('\n\n');
    printhdr('LOADING GLM DATA');
    fprintf('\n\n');

    savefilenamedata = fullfile(resultsdir, [resultsstring, mygroupnamefield, '_', scaling_string, '_', results_suffix, '.mat']);

    if exist(savefilenamedata,'file')
        fprintf('\nLoading %s regression results and maps from %s\n\n', analysis_type, savefilenamedata);
        load(savefilenamedata);
    else
        fprintf('\nNo saved results file %s. Skipping this analysis.', savefilenamedata);
        fprintf('\nRun prep_3a_run_second_level_regression_and_save.m to get %s regression results first.\n', analysis_type); 
        return
    end

else
    fprintf('\n%s %s found, displaying results\n\n', resultsvarname, analysis_type);

end

if ~dorobfit_parcelwise    
    
    results = regression_stats_results;
    
    if doBayes
        bayesian_results = bayesian_regression_stats_results;
    end
    
    if doTFCE
        tfce_results = tfce_regression_stats_results;
    end

else
    
    results = parcelwise_stats_results;

end

% Bayes factors come from prep_3a's VOXELWISE branch only - the parcelwise
% results file contains just parcelwise_stats_results - so doBayes on its own
% does not tell us whether they are available here. Without this, a parcelwise
% run with doBayes = true dies on an undefined bayesian_results.
has_bayes = doBayes && exist('bayesian_results','var') && ~isempty(bayesian_results);

% Same for TFCE: it is computed in prep_3a's voxelwise branch only, so a
% parcelwise results file has no tfce_regression_stats_results and doTFCE alone
% would send us into an undefined tfce_results.
has_tfce = doTFCE && exist('tfce_results','var') && ~isempty(tfce_results);

% Region tables for the UNCORRECTED TFCE map are off by default: an uncorrected
% TFCE map typically covers tens of thousands of voxels, so the table is long,
% slow to build (atlas labelling dominates c2a's runtime) and not something that
% would be reported. The montage is still shown. Set true in a2 to restore it.
if ~exist('dotables_tfce_unc','var') || isempty(dotables_tfce_unc)
    dotables_tfce_unc = false;
end

% Extent threshold for TFCE. Defaults to 0, i.e. none, and deliberately NOT to
% k_threshold_glm: TFCE already integrates cluster extent into the statistic
% itself - that is what the enhancement does - so a further extent filter counts
% extent twice. And when the map is thresholded on max-statistic FWE p-values,
% familywise error is already controlled across the whole search volume, which is
% the job an extent threshold is usually brought in to approximate. Applying
% k >= 50 on top discards valid FWE-significant voxels: on proj_moodbugs_wp2
% contrast 5 it removed all 42 of them and reported an empty map.
if ~exist('k_threshold_tfce','var') || isempty(k_threshold_tfce)
    k_threshold_tfce = 0;
end



%
% *MVPA*

if dobootstrap_mvpa_reg_cov
    
    mvpa_resultsvarname = 'mvpa_stats_results';
    mvpa_resultsstring = 'mvpa_stats_and_maps_';
    mvpa_analysis_type = algorithm_mvpa_reg_cov;

    if ~exist(mvpa_resultsvarname,'var')

        fprintf('\n\n');
        printhdr('LOADING MVPA DATA');
        fprintf('\n\n');

        savefilenamedata_mvpa = fullfile(resultsdir, ['mvpa_stats_and_maps_', mygroupnamefield, '_', scaling_string, '_', results_suffix, '.mat']);

        if exist(savefilenamedata_mvpa,'file')
            fprintf('\nLoading %s mvpa regression results and maps from %s\n\n', mvpa_analysis_type, savefilenamedata_mvpa);
            load(savefilenamedata_mvpa);
        else
            fprintf('\nNo saved results file %s. Skipping this analysis.', savefilenamedata_mvpa);
            fprintf('\nRun prep_3a_run_second_level_regression_and_save.m to get %s regression results first.\n', mvpa_analysis_type); 
            return
        end

    else
        fprintf('\n%s %s found, displaying results\n\n', mvpa_resultsvarname, mvpa_analysis_type);

    end

end
    

%% VISUALIZE GLM AND MVPA RESULTS FOR EACH CONTRAST
% -------------------------------------------------------------------------

region_objs_fdr = cell(1,size(results,2));
region_tables_fdr = cell(1,size(results,2));
region_tables_cov_fdr = cell(1,size(results,2));

region_objs_unc = cell(1,size(results,2));
region_tables_unc = cell(1,size(results,2));
region_tables_cov_unc = cell(1,size(results,2));

    if has_bayes
        region_objs_Bayes = cell(1,size(bayesian_results,2));
        region_tables_Bayes = cell(1,size(bayesian_results,2));
        region_tables_cov_Bayes = cell(1,size(bayesian_results,2));
    end
    
    if has_tfce
        % region output is produced for the REPORTED correction only (see
        % tfce_correction) - labelling regions against an atlas is the slowest
        % step in this script, and the maps below are saved either way.
        region_objs_tfce_corr = cell(1,size(tfce_results,2));
        region_tables_tfce_corr = cell(1,size(tfce_results,2));
        region_tables_cov_tfce_corr = cell(1,size(tfce_results,2));
        
        % both corrections' thresholded maps, saved regardless of which is reported
        tfce_stat_imgs_thr_fdr = cell(1,size(tfce_results,2));
        tfce_stat_imgs_thr_fwe = cell(1,size(tfce_results,2));

        region_objs_tfce_unc = cell(1,size(tfce_results,2));
        region_tables_tfce_unc = cell(1,size(tfce_results,2)); 
        region_tables_cov_tfce_unc = cell(1,size(tfce_results,2));
    end
        

    
for c = 1:size(results, 2) % number of contrasts or conditions
    
    %%
    % *GLM*

    analysisname = results{c}.analysis_name;
    names = results{c}.variable_names;
    
    names_string = names{1};
    
        for name = 2:size(names,2)
            names_string = [names_string,' ',names{name}];
        end
    
        if ~dorobfit_parcelwise

            t = results{c}.t;               % NOTE: this statistic_object is unthresholded AND unmasked (except for a brainmask)
            
            t = apply_mask(t,brainmask);    % re-apply brainmask just to be sure
            
            if exist('maskname_short','var')
                voxelsize_glmmask = diag(glmmask.volInfo.mat(1:3, 1:3))';
                if ~isequal(voxelsize_glmmask,t)
                    glmmask = resample_space(glmmask,t);
                end
            end
        
            glmmask.dat(glmmask.dat < 1) = 0;   % re-binarize mask, resample_space causes non-zero non-one values at inner cortical boundaries

            if apply_mask_before_fdr
                t = apply_mask(t, glmmask);
            end

        else

            t = results{c}.t_obj;           % NOTE: this statistic_object is thresholded at FDR q < 0.05, resampled to the space of the fmri_data_object and masked by the atlas in the previous script!
            k_threshold_glm = 0;            % we don't want an extent threshold for parcelwise as it could eliminate small parcels

        end

        if has_bayes

            BF = bayesian_results{c}.BF;    % NOTE: unthresholded in both cases, masked in case of parcelwise only

            if ~dorobfit_parcelwise

                if apply_mask_before_fdr
                    
                    for j = 1:size(BF,2)
                        BF(j) = apply_mask(BF(j), glmmask);

                    end
                    
                end

            end

        end
        
        % TFCE may have been restricted to a subset of contrasts via cons2tfce in
        % prep_3a, in which case the cells for the other contrasts are empty.
        % Report TFCE only where it was actually computed - dereferencing an empty
        % cell here would error out the whole script on the first such contrast.
        
        has_tfce_c = has_tfce && numel(tfce_results) >= c && ~isempty(tfce_results{c});
        
        if has_tfce && ~has_tfce_c
            fprintf('\nno TFCE results for contrast %d (%s) - not in cons2tfce; skipping TFCE for it\n\n', ...
                c, analysisname);
        end
        
        if has_tfce_c
            
            tfce_stat_img = tfce_results{c}.tfce_stat_img;  % NOTE: unthresholded and unmasked
            tfce_dat = tfce_results{c}.tfce_dat;
            
            % WHICH TFCE CORRECTION TO REPORT
            % -------------------------------
            % tfce_info.p_FWE holds the max-statistic FWE-corrected p-values.
            % They are already corrected, so they get thresholded 'unc' at
            % p_threshold_fwe further down; running FDR on them would correct
            % twice. The swap of .p happens HERE, before apply_mask, because
            % p_FWE is indexed over the unmasked voxel list - masking first
            % would misalign the two.
            
            if ~exist('tfce_correction','var') || isempty(tfce_correction)
                tfce_correction = 'fwe';
            end
            
            if ~exist('p_threshold_fwe','var') || isempty(p_threshold_fwe)
                p_threshold_fwe = 0.05;
            end
            
            % p_FWE was added to group_tfce_from_subject_maps only recently, so
            % results generated before that carry none. It is fully recoverable
            % from what they DO store - the observed TFCE map and the
            % max-statistic null - so recompute it rather than force a rerun of
            % the permutations, which is by far the most expensive step here.
            
            tfce_p_fwe = [];
            
            if isfield(tfce_results{c},'tfce_info')
                
                if isfield(tfce_results{c}.tfce_info,'p_FWE') && ~isempty(tfce_results{c}.tfce_info.p_FWE)
                    
                    tfce_p_fwe = tfce_results{c}.tfce_info.p_FWE;
                    
                elseif all(isfield(tfce_results{c}.tfce_info,{'TFCE_real','TFCE_null_max'}))
                    
                    n_perm_saved = numel(tfce_results{c}.tfce_info.TFCE_null_max);
                    
                    fprintf(['\nNOTE: no p_FWE stored for contrast %d - these TFCE results predate the FWE\n' ...
                             'implementation. Recomputing it from the saved max-statistic null:\n' ...
                             '%d permutations, so the finest attainable p is %.4f.\n\n'], ...
                             c, n_perm_saved, 1/(n_perm_saved+1));
                    
                    tfce_p_fwe = tfce_fwe_from_null(tfce_results{c}.tfce_info.TFCE_real, ...
                                                    tfce_results{c}.tfce_info.TFCE_null_max);
                    
                end
                
            end
            
            has_p_fwe = ~isempty(tfce_p_fwe);
            
            if ~has_p_fwe && ~strcmpi(tfce_correction,'fdr')
                warning('c2a:noTFCEfwe', ...
                    ['contrast %d carries neither p_FWE nor the max-statistic null needed to\n' ...
                     'recompute it, so FWE is unavailable. Reporting FDR instead.'], c);
                tfce_correction = 'fdr';
            end
            
            tfce_stat_img_fwe = [];
            
            if has_p_fwe
                % swap uncorrected for FWE-corrected p BEFORE masking, so the p
                % vector and the image voxels stay aligned
                tfce_stat_img_fwe = tfce_stat_img;
                tfce_stat_img_fwe.p = tfce_p_fwe;
            end
            
            if apply_mask_before_fdr
                
                tfce_stat_img = apply_mask(tfce_stat_img, glmmask);
                
                if ~isempty(tfce_stat_img_fwe)
                    tfce_stat_img_fwe = apply_mask(tfce_stat_img_fwe, glmmask);
                end
                
                % Lukas' original code
                % causes mismatch in length of .dat fields between 
                % tfce_stat_img and tfce_dat in some cases, for unknown reasons
                
%                 tfce_dat = apply_mask(tfce_dat, glmmask);
                
            end
            
        end
    
    fprintf('\n\n');
    printhdr(['CONTRAST #', num2str(c), ': ', upper(analysisname)]);
    fprintf('\n\n');
    
    fprintf('\nREGRESSORS: %s\n\n', names_string);
    
    % summary() is a METHOD of the glm_map object that prep_3a's voxelwise branch
    % returns. The parcelwise branch returns a plain struct, for which MATLAB
    % resolves summary() to the first one on the path - here
    % CanlabCore/OptimizeDesign11/other_functions/summary.m, which immediately
    % fails on its own missing 'defaults_optimize'. Call it only when it really
    % is a method of this object.
    if ismethod(results{c}, 'summary')
        summary(results{c})
    end
    fprintf('\n\n');
    
    num_effects = size(t.dat, 2);   % number of regressors
    
    % BETWEEN-SUBJECT REGRESSORS & INTERCEPT: FDR corrected
    % -----------------------------------------------------
    
    fprintf('\n\n');
    printhdr('FDR-CORRECTED GLM RESULTS');
    fprintf('\n\n');
    
    fprintf ('\nMONTAGE GLM RESULTS AT FDR q < %1.4f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', q_threshold_glm, k_threshold_glm, analysisname, names_string, mask_string, scaling_string);
    
    o2 = canlab_results_fmridisplay([], 'multirow', num_effects);
    
        for j = 1:num_effects

            tj = get_wh_image(t, j);
                    
                if ~dorobfit_parcelwise
                    
                    tj = threshold(tj, q_threshold_glm, 'fdr', 'k', k_threshold_glm); 
                        
                end

            datsig = tj.dat(logical(tj.sig));
            datsigneg = datsig(datsig<0);
            datsigpos = datsig(datsig>0);

                if isempty(datsigneg) && ~isempty(datsigpos)
                    
                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.9 .4 0], 'maxcolor', [1 1 0]);%, 'cmaprange', [min(datsigpos) max(datsigpos)]);
                    
                elseif isempty(datsigpos) && ~isempty(datsigneg)
                    
                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.1 .8 .8], 'maxcolor', [.1 .1 .8]);%, 'cmaprange', [min(datsigneg) max(datsigneg)]);
                    
                else
                
                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'splitcolor',{[.1 .8 .8] [.1 .1 .8] [.9 .4 0] [1 1 0]});%, 'cmaprange', [min(datsigneg) max(datsigneg) min(datsigpos) max(datsigpos)]);
                    
                end
                
                if num_effects < 4
                    o2 = legend(o2);
                end
                
            o2 = title_montage(o2, 2*j, [analysisname ' FDR ' num2str(q_threshold_glm) ' ' names{j} ' ' mask_string ' ' scaling_string]);

        end % for loop over regressors in model
    
    figtitle = sprintf('%s_%s_%1.4f_FDR_montage_%s_%s_%s', analysisname, results_suffix, q_threshold_glm, names_string, mask_string, scaling_string);
    set(gcf, 'Tag', figtitle); plugin_set_figure_size;
    drawnow, snapnow;
    
        if save_figures_glm
            plugin_save_figure;
        end
        
    clear o2, clear figtitle, clear j, clear tj
    
    fprintf ('\nTABLES AND MONTAGE REGIONCENTERS GLM RESULTS AT FDR q < %1.4f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', q_threshold_glm, k_threshold_glm, analysisname, names_string, mask_string, scaling_string);
    
        region_fdr = cell(1,num_effects);
        table_fdr = cell(1,num_effects);
        table_cov_fdr = cell(1,num_effects);
        
        for j = 1:num_effects

            fprintf ('\nTABLE GLM RESULTS AT FDR q < %1.4f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', q_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);

            tj = get_wh_image(t, j);
                    
                if ~dorobfit_parcelwise
                    
                    tj = threshold(tj, q_threshold_glm, 'fdr', 'k', k_threshold_glm); 
                        
                end

            r = region(tj);
            if ~isempty(r)
                r(cat(1, r.numVox) < k_threshold_glm) = [];
            end
            
            if ~isempty(r)
            
                if exist('combined_atlas','var')
                    
                    [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r,'atlas_obj',combined_atlas);                            % print results summary table, label using atlasname_glm, and split positive and negative regions
                    
                    r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object
                    
                    [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                        r_table_cov] = table_of_atlas_regions_covered(tj,'atlas',combined_atlas);           % print results details table with regions covered and label using atlasname_glm
                    
                else
                    
                    [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r);                                                       % print results summary table, label using default atlas, and split positive and negative regions
                    
                    r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object
                    
                    [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                        r_table_cov] = table_of_atlas_regions_covered(tj,'atlas',combined_atlas);           % print results details table with regions covered and label using default atlas

                end
            
                region_fdr{j} = r;
                table_fdr{j} = r_table;
                table_cov_fdr{j} = r_table_cov;

                % Montage of regions in table (plot and save)
                
                fprintf ('\nMONTAGE REGIONCENTERS GLM RESULTS AT FDR q < %1.4f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', q_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);
                
                % regioncenters puts one titled panel per region on a single figure, which
                % stops being readable - and stops being quick - once there are many.
                if ~exist('max_regioncenters_montage','var') || isempty(max_regioncenters_montage), max_regioncenters_montage = 21; end

                if numel(r) < max_regioncenters_montage

                o3 = montage(r, 'regioncenters', 'splitcolor',{[.1 .8 .8] [.1 .1 .8] [.9 .4 0] [1 1 0]});

                % Activate, name, and save figure
                figtitle = sprintf('%s_%s_%1.4f_FDR_regions_%s_%s_%s', analysisname, results_suffix, q_threshold_glm, names{j}, mask_string, scaling_string);
                set(gcf, 'Tag', figtitle); plugin_set_figure_size;
                drawnow, snapnow;
                    if save_figures_glm
                        plugin_save_figure;
                    end
                clear o3, clear figtitle, clear j, clear tj, clear r, clear rpos rneg r_cov, clear r_table*

                else

                    fprintf('\nregioncenters montage skipped: %d regions, at or above the display limit of %d\n\n', numel(r), max_regioncenters_montage);

                end

            end % conditional montage plot if there are regions to show
            
        end % for loop over regressors in model
        
        region_objs_fdr{c} = region_fdr;
        region_tables_fdr{c} = table_fdr;
        region_tables_cov_fdr{c} = table_cov_fdr;
        
  
    % BETWEEN-SUBJECT REGRESSORS & INTERCEPT: uncorrected
    % ---------------------------------------------------
    
    fprintf('\n\n');
    printhdr('UNCORRECTED GLM RESULTS');
    fprintf('\n\n');
    
    fprintf ('\nMONTAGE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_glm, analysisname, names_string, mask_string, scaling_string);
    
    o2 = canlab_results_fmridisplay([], 'multirow', num_effects);
    
        for j = 1:num_effects

            tj = get_wh_image(t, j);
            
            tj = threshold(tj, p_threshold_glm, 'unc', 'k', k_threshold_glm); 

            datsig = tj.dat(logical(tj.sig));
            datsigneg = datsig(datsig<0);
            datsigpos = datsig(datsig>0);

                if isempty(datsigneg) && ~isempty(datsigpos)

                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.9 .4 0], 'maxcolor', [1 1 0]);%, 'cmaprange', [min(datsigpos) max(datsigpos)]);

                elseif isempty(datsigpos) && ~isempty(datsigneg)

                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.1 .8 .8], 'maxcolor', [.1 .1 .8]);%, 'cmaprange', [min(datsigneg) max(datsigneg)]);

                else

                    o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'splitcolor',{[.1 .8 .8] [.1 .1 .8] [.9 .4 0] [1 1 0]});%, 'cmaprange', [min(datsigneg) max(datsigneg) min(datsigpos) max(datsigpos)]);

                end
                
                if num_effects < 4
                    o2 = legend(o2);
                end
                
            o2 = title_montage(o2, 2*j, [analysisname ' unc ' num2str(p_threshold_glm) ' ' names{j} ' ' mask_string ' ' scaling_string]);
        
        end % for loop over regressors in model
    
    figtitle = sprintf('%s_%s_%1.4f_unc_montage_%s_%s_%S', analysisname, results_suffix, p_threshold_glm, names_string, mask_string, scaling_string);
    set(gcf, 'Tag', figtitle); plugin_set_figure_size;
    drawnow, snapnow;
    
        if save_figures_glm
            plugin_save_figure;
        end
        
    clear o2, clear figtitle, clear j, clear tj
    
    fprintf ('\nTABLES AND MONTAGE REGIONCENTERS GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_glm, analysisname, names_string, mask_string, scaling_string);
        
        region_unc = cell(1,num_effects);
        table_unc = cell(1,num_effects);
        table_cov_unc = cell(1,num_effects);
    
        for j = 1:num_effects

            fprintf ('\nTABLE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);

            tj = get_wh_image(t, j);

            tj = threshold(tj, p_threshold_glm, 'unc', 'k', k_threshold_glm); 

            r = region(tj);
            if ~isempty(r)
                r(cat(1, r.numVox) < k_threshold_glm) = [];
            end
            
            if ~isempty(r)
            
                if exist('combined_atlas','var')
                    
                    [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r,'atlas_obj',combined_atlas);                            % print results summary table, label using atlasname_glm, and split positive and negative regions
                    
                    r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object
                    
                    [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                        r_table_cov] = table_of_atlas_regions_covered(tj,'atlas',combined_atlas);           % print results details table with regions covered and label using atlasname_glm
                    
                else
                    
                    [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r);                                                       % print results summary table, label using default atlas, and split positive and negative regions
                    
                    r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object
                    
                    [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                        r_table_cov] = table_of_atlas_regions_covered(tj,'atlas',combined_atlas);           % print results details table with regions covered and label using default atlas

                end
            
                region_unc{j} = r;
                table_unc{j} = r_table;
                table_cov_unc{j} = r_table_cov;

                % Montage of regions in table (plot and save)
                
                fprintf ('\nMONTAGE REGIONCENTERS GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);
                
                % regioncenters puts one titled panel per region on a single figure, which
                % stops being readable - and stops being quick - once there are many.
                if ~exist('max_regioncenters_montage','var') || isempty(max_regioncenters_montage), max_regioncenters_montage = 21; end

                if numel(r) < max_regioncenters_montage

                o3 = montage(r, 'regioncenters', 'splitcolor',{[.1 .8 .8] [.1 .1 .8] [.9 .4 0] [1 1 0]});

                % Activate, name, and save figure
                figtitle = sprintf('%s_%s_%1.4f_unc_regions_%s_%s_%s', analysisname, results_suffix, p_threshold_glm, names{j}, mask_string, scaling_string);
                set(gcf, 'Tag', figtitle); plugin_set_figure_size;
                drawnow, snapnow;
                    if save_figures_glm
                        plugin_save_figure;
                    end
                clear o3, clear figtitle, clear j, clear tj, clear r, clear rpos rneg r_cov, clear r_table*

                else

                    fprintf('\nregioncenters montage skipped: %d regions, at or above the display limit of %d\n\n', numel(r), max_regioncenters_montage);

                end

            end % conditional montage plot if there are regions to show
        
        end % loop over regressors
        
    region_objs_unc{c} = region_unc;
    region_tables_unc{c} = table_unc;
    region_tables_cov_unc{c} = table_cov_unc;

    
    % BETWEEN-SUBJECT REGRESSORS & INTERCEPT: Bayesian
    % ------------------------------------------------
    
    if has_bayes
    
        fprintf('\n\n');
        printhdr('BAYESIAN GLM RESULTS');
        fprintf('\n\n');

        fprintf ('\nMONTAGE BAYESIAN GLM RESULTS AT |BF| > %1.2f, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', BF_threshold_glm, analysisname, names_string, mask_string, scaling_string);

        o2 = canlab_results_fmridisplay([], 'multirow', num_effects); 

            for j = 1:num_effects

                BFj = BF(1,j);
                
                BFj = threshold(BFj, [-2*(log(BF_threshold_glm)) 2*(log(BF_threshold_glm))], 'raw-outside'); 

                datsig = BFj.dat(logical(BFj.sig));
                datsigneg = datsig(datsig<0);
                datsigpos = datsig(datsig>0);
                
                    if isempty(datsigneg) && ~isempty(datsigpos)

                        o2 = addblobs(o2, region(BFj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[0 0.25 0], 'maxcolor', [0 1 0]);%, 'cmaprange', [min(datsigpos) max(datsigpos)]);

                    elseif isempty(datsigpos) && ~isempty(datsigneg)

                        o2 = addblobs(o2, region(BFj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.25 0 0], 'maxcolor', [1 0 0]);%, 'cmaprange', [min(datsigneg) max(datsigneg)]);

                    else

                        o2 = addblobs(o2, region(BFj), 'wh_montages', (2*j)-1:2*j, 'splitcolor',{[.25 0 0] [1 0 0] [0 0.25 0] [0 1 0]});%, 'cmaprange', [min(datsigneg) max(datsigneg) min(datsigpos) max(datsigpos)]); % red in favor of H0, green in favor of H1 for BF maps

                    end

                    if num_effects < 4
                        o2 = legend(o2);
                    end
                
                o2 = title_montage(o2, 2*j, [analysisname ' |BF| > ' num2str(BF_threshold_glm) ' ' names{j} ' ' mask_string ' ' scaling_string]);

            end % for loop over regressors in model

        figtitle = sprintf('%s_%s_%1.4f_Bayes_montage_%s_%s_%s', analysisname, results_suffix, BF_threshold_glm, names_string, mask_string, scaling_string);
        set(gcf, 'Tag', figtitle); plugin_set_figure_size;
        drawnow, snapnow;

            if save_figures_glm
                plugin_save_figure;
            end

        clear o2, clear figtitle, clear j, clear BFj

        fprintf ('\nTABLES AND MONTAGE REGIONCENTERS BAYESIAN GLM RESULTS AT |BF| > %1.2f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', BF_threshold_glm, k_threshold_glm, analysisname, names_string, mask_string, scaling_string);

            region_Bayes = cell(1,num_effects);
            table_Bayes = cell(1,num_effects);
            table_cov_Bayes = cell(1,num_effects);
        
            for j = 1:num_effects

                fprintf ('\nTABLE BAYESIAN GLM RESULTS AT |BF| > %1.2f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', BF_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);

                BFj = BF(1,j);
                BFj = threshold(BFj, [-2*(log(BF_threshold_glm)) 2*(log(BF_threshold_glm))], 'raw-outside'); 

                r = region(BFj);
                
                if ~isempty(r)
                r(cat(1, r.numVox) < k_threshold_glm) = [];
            end
                
                if ~isempty(r)
                
                    if exist('combined_atlas','var')

                        [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r,'atlas_obj',combined_atlas);                            % print results summary table, label using atlasname_glm, and split positive and negative regions

                        r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object

                        [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                            r_table_cov] = table_of_atlas_regions_covered(BFj,'atlas',combined_atlas);          % print results details table with regions covered and label using atlasname_glm

                    else

                        [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@table, r);                                                       % print results summary table, label using default atlas, and split positive and negative regions

                        r = [rpos rneg];                                                                        % re-concatenate positive and negative regions into one region object

                        [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                            r_table_cov] = table_of_atlas_regions_covered(BFj,'atlas',combined_atlas);          % print results details table with regions covered and label using default atlas

                    end

                    region_Bayes{j} = r;
                    table_Bayes{j} = r_table;
                    table_cov_Bayes{j} = r_table_cov;

                    % Montage of regions in table (plot and save)

                    fprintf ('\nMONTAGE REGIONCENTERS BAYESIAN GLM RESULTS AT |BF| > %1.2f, k = %d, CONTRAST: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', BF_threshold_glm, k_threshold_glm, analysisname, names{j}, mask_string, scaling_string);

                    % regioncenters puts one titled panel per region on a single figure, which
                    % stops being readable - and stops being quick - once there are many.
                    if ~exist('max_regioncenters_montage','var') || isempty(max_regioncenters_montage), max_regioncenters_montage = 21; end

                    if numel(r) < max_regioncenters_montage

                    o3 = montage(r, 'regioncenters', 'splitcolor',{[.25 0 0] [1 0 0] [0 0.25 0] [0 1 0]});

                    % Activate, name, and save figure
                    figtitle = sprintf('%s_%s_%1.4f_Bayes_regions_%s_%s_%s', analysisname, results_suffix, p_threshold_glm, names{j}, mask_string, scaling_string);
                    set(gcf, 'Tag', figtitle); plugin_set_figure_size;
                    drawnow, snapnow;
                        if save_figures_glm
                            plugin_save_figure;
                        end
                    clear o3, clear figtitle, clear j, clear BFj, clear r, clear rpos rneg r_cov, clear r_table*

                    else

                        fprintf('\nregioncenters montage skipped: %d regions, at or above the display limit of %d\n\n', numel(r), max_regioncenters_montage);

                    end

                end % conditional montage plot if there are regions to show

            end % for loop over regressors
            
        region_objs_Bayes{c} = region_Bayes;
        region_tables_Bayes{c} = table_Bayes;
        region_tables_cov_Bayes{c} = table_cov_Bayes;
            
    end % if loop doBayes
    
    
    if has_tfce_c
        
        % BETWEEN-SUBJECT REGRESSORS or INTERCEPT: TFCE, CORRECTED
        % --------------------------------------------------------
        % Both corrections are thresholded and saved; only the one named by
        % tfce_correction gets montages and region tables below.
        
        tfce_stat_img_thr_fdr = threshold(tfce_stat_img, q_threshold_glm, 'fdr', 'k', k_threshold_tfce);
        
        if ~isempty(tfce_stat_img_fwe)
            tfce_stat_img_thr_fwe = threshold(tfce_stat_img_fwe, p_threshold_fwe, 'unc', 'k', k_threshold_tfce);
        else
            tfce_stat_img_thr_fwe = [];
        end
        
        switch lower(tfce_correction)
            
            case 'fwe'
                tfce_stat_img_thr_corr = tfce_stat_img_thr_fwe;
                tfce_corr_label        = 'FWE';
                tfce_corr_thresh       = p_threshold_fwe;
                
            case 'fdr'
                tfce_stat_img_thr_corr = tfce_stat_img_thr_fdr;
                tfce_corr_label        = 'FDR';
                tfce_corr_thresh       = q_threshold_glm;
                
            otherwise
                error('unrecognized tfce_correction ''%s'', use ''fwe'' or ''fdr''', tfce_correction);
                
        end
        
        fprintf('\n\n');
        printhdr(sprintf('TFCE %s-CORRECTED GLM RESULTS', tfce_corr_label));
        fprintf('\n\n');
        
        % Lukas' original code
        
        % based on masked versions or tfce_stat_img and tfce_dat, 
        % which leads to mismatched length of .dat causing 
        % the function call to throw an error - see line 527-
        
%         tfce_dat_thr_fdr = thresholded_fmri_data_from_statistic_image(tfce_stat_img_thr_fdr, tfce_dat.dat, combined_atlas, q_threshold_glm, 'tfce', 'fdr', k_threshold_glm);

        % Lixin's fix (thanks!)
        
        if any(tfce_stat_img_thr_corr.sig(:))
            
            % keep both inputs as CANLab objects so voxel-space and removed
            % voxels information are preserved
            tfce_dat_thr_corr = apply_mask(tfce_dat, tfce_stat_img_thr_corr);
            
            if isempty(tfce_dat_thr_corr.dat)
                tfce_dat_thr_corr = [];
            end
            
        else
            
            tfce_dat_thr_corr = [];
            
        end


        if ~isempty(tfce_dat_thr_corr)
        
            % WHOLE-BRAIN MONTAGE

                switch design_matrix_type

                    case 'onesample'

                        fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, groupnames_string, mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_%s_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, groupnames_string, mask_string, scaling_string);

                    case 'group'

                        fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_%s_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                    case 'custom'

                        if exist('nuisance_covs','var') && ~isempty(nuisance_covs)

                            fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, NUISANCE COVARIATE(S): %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_%s_montage_%s_nuisance_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);

                        else

                            fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_%s_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                        end

                end

            % montage() on a DATA object routes through canlab_results_fmridisplay WITHOUT
            % create_figure, so it draws into whatever figure is current - which is the
            % previous block's montage. Verified: after canlab_results_fmridisplay the
            % figure count stays 1 and the axes accumulate, so the TFCE blobs landed on top
            % of the Bayes montage and both were captured in one snapnow. Open a fresh
            % figure first. (region montages are fine - they go through create_figure.)
            figure;

            o2 = montage(tfce_dat_thr_corr,'mincolor',[0.47 0.11 0.43], 'maxcolor', [0.94 0.98 0.13]);
            o2 = title_montage(o2, 5, sprintf('tfce %s p < %s %s %s %s %s', tfce_corr_label, num2str(tfce_corr_thresh), regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string));
            set(gcf, 'Tag', figtitle); plugin_set_figure_size;
            drawnow, snapnow;
                if save_figures_glm
                    plugin_save_figure;
                end
            clear o2, clear figtitle

            % REGION MONTAGE & TABLE

                switch design_matrix_type

                    case 'onesample'

                        fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, groupnames_string, mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_%s_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, groupnames_string, mask_string, scaling_string);

                    case 'group'

                        fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_%s_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                    case 'custom'

                        if exist('nuisance_covs','var') && ~isempty(nuisance_covs)

                            fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, NUISANCE COVARIATE(S): %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_%s_regions_%s_nuisance_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);

                        else

                            fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT %s p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', tfce_corr_label, tfce_corr_thresh, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_%s_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, tfce_corr_thresh, tfce_corr_label, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                        end

                end

            region_tfce_corr = cell(1);
            table_tfce_corr = cell(1);
            table_cov_tfce_corr = cell(1);

            r = region(tfce_dat_thr_corr);
            if ~isempty(r)
                r(cat(1, r.numVox) < k_threshold_tfce) = [];
            end
            % r is a region ARRAY; a scalar assignment to a property of every element
            % is not allowed ('Assigning to N elements using a simple assignment
            % statement is not supported'). deal distributes it over the
            % comma-separated list. Guarded because the extent filter above can
            % empty r, and indexing a property of an empty region array also errors.
            if ~isempty(r)
                [r.Z_descrip] = deal('TFCE');
            end
                if ~isempty(r)

                    if exist('combined_atlas','var')

                        [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@LaBGAScore_region_table, r,'atlas_obj',combined_atlas);                                            % print results summary table, label using atlasname_glm, and split positive and negative regions

                        r = [rpos rneg];                                                                                        % re-concatenate positive and negative regions into one region object

                        [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                            r_table_cov] = table_of_atlas_regions_covered(tfce_dat_thr_corr,'atlas',combined_atlas);             % print results details table with regions covered and label using atlasname_glm

                    else

                        [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@LaBGAScore_region_table, r);                                                                       % print results summary table, label using default atlas, and split positive and negative regions

                        r = [rpos rneg];                                                                                        % re-concatenate positive and negative regions into one region object

                        [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                            r_table_cov] = table_of_atlas_regions_covered(tfce_dat_thr_corr,'atlas',combined_atlas);             % print results details table with regions covered and label using default atlas

                    end     

                    region_tfce_corr{1} = r;
                    table_tfce_corr{1} = r_table;
                    table_cov_tfce_corr{1} = r_table_cov;

                    % Montage of regions in table (plot and save)

                    % regioncenters puts one titled panel per region on a single figure, which
                    % stops being readable - and stops being quick - once there are many.
                    if ~exist('max_regioncenters_montage','var') || isempty(max_regioncenters_montage), max_regioncenters_montage = 21; end

                    if numel(r) < max_regioncenters_montage

                    o3 = montage(r, 'regioncenters', 'mincolor',[0.47 0.11 0.43], 'maxcolor', [0.94 0.98 0.13]);

                    % Activate, name, and save figure
                    set(gcf, 'Tag', figtitle); plugin_set_figure_size;
                    drawnow, snapnow;
                        if save_figures_glm
                            plugin_save_figure;
                        end
                    clear o3, clear figtitle, clear j, clear r, clear rpos rneg r_cov, clear r_table*

                    else

                        fprintf('\nregioncenters montage skipped: %d regions, at or above the display limit of %d\n\n', numel(r), max_regioncenters_montage);

                    end

                end % conditional montage plot if there are regions to show

            region_objs_tfce_corr{c} = region_tfce_corr;
            region_tables_tfce_corr{c} = table_tfce_corr;
            region_tables_cov_tfce_corr{c} = table_cov_tfce_corr;
            
        else
            
            fprintf('No suprathreshold voxels for this contrast AT %s p < %1.4f, k = %d',tfce_corr_label, tfce_corr_thresh, k_threshold_glm);
            
        end

        tfce_stat_imgs_thr_fdr{c} = tfce_stat_img_thr_fdr;
        tfce_stat_imgs_thr_fwe{c} = tfce_stat_img_thr_fwe;

        % BETWEEN-SUBJECT REGRESSORS or INTERCEPT: TFCE uncorrected
        % ---------------------------------------------------------
            
        fprintf('\n\n');
        printhdr('TFCE UNCORRECTED GLM RESULTS');
        fprintf('\n\n');
        
        tfce_stat_img_thr_unc = threshold(tfce_stat_img, p_threshold_glm, 'unc', 'k', k_threshold_tfce);
        
        % Lukas' code
        
        % based on masked versions or tfce_stat_img and tfce_dat, 
        % which leads to mismatched length of .dat causing 
        % the function call to throw an error - see line 527 -
        
%         tfce_dat_thr_unc = thresholded_fmri_data_from_statistic_image(tfce_stat_img_thr_unc, tfce_dat.dat, combined_atlas, p_threshold_glm, 'tfce', 'unc', k_threshold_glm);

        % Lixin's fix (thanks!)
        
        if any(tfce_stat_img_thr_unc.sig(:))
            
            % keep both inputs as CANLab objects so voxel-space and removed
            % voxels information are preserved
            tfce_dat_thr_unc = apply_mask(tfce_dat, tfce_stat_img_thr_unc);
            
            if isempty(tfce_dat_thr_unc.dat)
                tfce_dat_thr_unc = [];
            end
            
        else
            
            tfce_dat_thr_unc = [];
            
        end

        
        if ~isempty(tfce_dat_thr_unc)
        
            % WHOLE-BRAIN MONTAGE

                switch design_matrix_type

                    case 'onesample'

                        fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, groupnames_string, mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_UNC_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, groupnames_string, mask_string, scaling_string);

                    case 'group'

                        fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                        figtitle = sprintf('%s_TFCE_%1.4f_UNC_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                    case 'custom'

                        if exist('nuisance_covs','var') && ~isempty(nuisance_covs)

                            fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, NUISANCE COVARIATE(S): %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_UNC_montage_%s_nuisance_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);

                        else

                            fprintf ('\nMONTAGE VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_UNC_montage_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                        end

                end

            % montage() on a DATA object routes through canlab_results_fmridisplay WITHOUT
            % create_figure, so it draws into whatever figure is current - which is the
            % previous block's montage. Verified: after canlab_results_fmridisplay the
            % figure count stays 1 and the axes accumulate, so the TFCE blobs landed on top
            % of the Bayes montage and both were captured in one snapnow. Open a fresh
            % figure first. (region montages are fine - they go through create_figure.)
            figure;

            o2 = montage(tfce_dat_thr_unc,'mincolor',[0.47 0.11 0.43], 'maxcolor', [0.94 0.98 0.13]);
            % same numeric-concatenation bug that was fixed for the corrected title:
            % p_threshold_glm is a NUMBER, so ['tfce q < ' 0.005 ...] concatenated
            % char(0.005), a control character, not the text "0.005". Also this map is
            % thresholded UNCORRECTED, so it is a p, not a q.
            o2 = title_montage(o2, 5, sprintf('tfce uncorrected p < %s %s %s %s %s', num2str(p_threshold_glm), regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string));
            set(gcf, 'Tag', figtitle); plugin_set_figure_size;
            drawnow, snapnow;
                if save_figures_glm
                    plugin_save_figure;
                end
            clear o2, clear figtitle

            % Region tables for the UNCORRECTED TFCE map are gated: see dotables_tfce_unc
            % above. The montage is always shown; only the table and regioncenters are
            % skipped, and the accumulators below stay defined so the save block works.
            if dotables_tfce_unc

                % REGION MONTAGE & TABLE

                    switch design_matrix_type

                        case 'onesample'

                            fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, groupnames_string, mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_UNC_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, groupnames_string, mask_string, scaling_string);

                        case 'group'

                            fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                            figtitle = sprintf('%s_TFCE_%1.4f_UNC_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                        case 'custom'

                            if exist('nuisance_covs','var') && ~isempty(nuisance_covs)

                                fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, NUISANCE COVARIATE(S): %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);
                                figtitle = sprintf('%s_TFCE_%1.4f_UNC_regions_%s_nuisance_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_nuisance)), mask_string, scaling_string);

                            else

                                fprintf ('\nTABLES AND MONTAGE REGIONCENTERS VOXELWISE TFCE GLM RESULTS AT UNCORRECTED p < %1.4f, k = %d, EFFECT: %s, REGRESSOR: %s, MASK: %s, SCALING: %s\n\n', p_threshold_glm, k_threshold_tfce, regression_stats_results{c}.analysis_name, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);
                                figtitle = sprintf('%s_TFCE_%1.4f_UNC_regions_%s_%s_%s', regression_stats_results{c}.analysis_name, p_threshold_glm, char(regression_stats_results{c}.variable_names(regression_stats_results{c}.wh_interest)), mask_string, scaling_string);

                            end

                    end

                region_tfce_unc = cell(1);
                table_tfce_unc = cell(1);
                table_cov_tfce_unc = cell(1);

                r = region(tfce_dat_thr_unc, 'noverbose');
                if ~isempty(r)
                    r(cat(1, r.numVox) < k_threshold_tfce) = [];
                end
                % r is a region ARRAY; a scalar assignment to a property of every element
                % is not allowed ('Assigning to N elements using a simple assignment
                % statement is not supported'). deal distributes it over the
                % comma-separated list. Guarded because the extent filter above can
                % empty r, and indexing a property of an empty region array also errors.
                if ~isempty(r)
                    [r.Z_descrip] = deal('TFCE');
                end
                    if ~isempty(r)

                        if exist('combined_atlas','var')

                            [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@LaBGAScore_region_table, r,'atlas_obj',combined_atlas);                                            % print results summary table, label using atlasname_glm, and split positive and negative regions

                            r = [rpos rneg];                                                                                        % re-concatenate positive and negative regions into one region object

                            [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                                r_table_cov] = table_of_atlas_regions_covered(tfce_dat_thr_unc,'atlas',combined_atlas);             % print results details table with regions covered and label using atlasname_glm

                        else

                            [rpos, rneg, r_table] = LaBGAScore_region_table_safe(@LaBGAScore_region_table, r);                                                                       % print results summary table, label using default atlas, and split positive and negative regions

                            r = [rpos rneg];                                                                                        % re-concatenate positive and negative regions into one region object

                            [r_table_cov_pos, r_table_cov_neg, r_cov, r_table_cov_excl, ~, ~, ...
                                r_table_cov] = table_of_atlas_regions_covered(tfce_dat_thr_unc,'atlas',combined_atlas);             % print results details table with regions covered and label using default atlas

                        end     

                        region_tfce_unc{1} = r;
                        table_tfce_unc{1} = r_table;
                        table_cov_tfce_unc{1} = r_table_cov;

                        % Montage of regions in table (plot and save)

                        % regioncenters puts one titled panel per region on a single figure, which
                        % stops being readable - and stops being quick - once there are many.
                        if ~exist('max_regioncenters_montage','var') || isempty(max_regioncenters_montage), max_regioncenters_montage = 21; end

                        if numel(r) < max_regioncenters_montage

                        o3 = montage(r, 'regioncenters', 'mincolor',[0.47 0.11 0.43], 'maxcolor', [0.94 0.98 0.13]);

                        % Activate, name, and save figure
                        set(gcf, 'Tag', figtitle); plugin_set_figure_size;
                        drawnow, snapnow;
                            if save_figures_glm
                                plugin_save_figure;
                            end
                        clear o3, clear figtitle, clear j, clear tj, clear r, clear rpos rneg r_cov, clear r_table*

                        else

                            fprintf('\nregioncenters montage skipped: %d regions, at or above the display limit of %d\n\n', numel(r), max_regioncenters_montage);

                        end

                    end % conditional montage plot if there are regions to show


            else

                region_tfce_unc = cell(1); table_tfce_unc = cell(1); table_cov_tfce_unc = cell(1);
                fprintf('\nregion table for the uncorrected TFCE map skipped (dotables_tfce_unc = false)\n\n');

            end

            region_objs_tfce_unc{c} = region_tfce_unc;
            region_tables_tfce_unc{c} = table_tfce_unc;
            region_tables_cov_tfce_unc{c} = table_cov_tfce_unc;
        
        end % if loop TFCE unc
        
    end % if loop TFCE
        
          
    %%
    % *MVPA*
    
    if dobootstrap_mvpa_reg_cov
        
        fprintf('\n\n');
        printhdr(['CONTRAST #', num2str(c), ': ', upper(analysisname)]);
        fprintf('\n\n');
    
        fprintf('\nREGRESSOR: %s\n\n', names_string);
        
        mvpa_bs_stats_results = cell(1,size(results,2));
        
        for covar = 1:size(mvpa_stats_results,2)
            mvpa_results{covar} = mvpa_stats_results{c,covar};
            mvpa_fmri_dats{covar} = mvpa_dats{c,covar};
        end
        
        if isempty(cons2boot) || ismember(c,cons2boot)
        
            mvpa_num_effects = size(mvpa_results,2);

            mvpa_bs_stats = cell(1,mvpa_num_effects);

            if strcmp(parallelstr_mvpa_reg_cov,'parallel')

                delete(gcp('nocreate'));
                LaBGAScore_smart_parallel_pool_setup

            end

            for j = 1:mvpa_num_effects

                fprintf('\n\n');
                printhdr('BOOTSTRAPPING MVPA WEIGHT MAP');
                fprintf('\n\n');

                t0_boot = tic;
                
                switch algorithm_mvpa_reg_cov   % TO DO: add optimal alpha and lambda lasso parameters from nested cv in predict() run in prep_3a, should be stored in stats.other_output somewhere
                    
                    case 'cv_lassopcr'

                        [~ , mvpa_bs_stats{j}] = predict(mvpa_fmri_dats{j}, 'algorithm_name', algorithm_mvpa_reg_cov,...
                            'bootsamples', boot_n_mvpa_reg_cov, 'nfolds', 1, 'error_type', 'mse', ...
                            parallelstr_mvpa_reg_cov, 'verbose', 0);
                        
                    case 'cv_lassopcr_matlab'
                        
                        [~ , mvpa_bs_stats{j}] = predict(mvpa_fmri_dats{j}, 'algorithm_name', algorithm_mvpa_reg_cov,...
                            'bootsamples', boot_n_mvpa_reg_cov, 'nfolds', 1, 'error_type', 'mse', ...
                            parallelstr_mvpa_reg_cov, 'verbose', 0);
                        
                    otherwise
                        
                        [~ , mvpa_bs_stats{j}] = predict(mvpa_fmri_dats{j}, 'algorithm_name', algorithm_mvpa_reg_cov,...
                            'bootsamples', boot_n_mvpa_reg_cov, 'nfolds', 1, 'error_type', 'mse', ...
                            parallelstr_mvpa_reg_cov, 'verbose', 0);
                        
                end

                t_end_boot = toc(t0_boot);

            end % for loop over regressors

            mvpa_bs_stats_results{c} = mvpa_bs_stats;

            fprintf('\n\n');
            printhdr('PLOTTING BOOTSTRAPPED MVPA WEIGHT MAPS');
            fprintf('\n\n');

            fprintf ('\nMONTAGE BOOTSTRAPPED %s RESULTS AT FDR q < %1.4f, k = %d, CONTRAST: %s, REGRESSORS: %s, MASK: %s, SCALING: %s\n\n', upper(algorithm_mvpa_reg_cov), q_threshold_mvpa_reg_cov, k_threshold_mvpa_reg_cov, analysisname, names_string, mask_string, scaling_string);

            o2 = canlab_results_fmridisplay([], 'multirow', mvpa_num_effects);

                for j = 1:mvpa_num_effects

                    tj = mvpa_bs_stats{j}.weight_obj;
                    
                        if apply_mask_before_fdr
                            tj = apply_mask(tj, glmmask);
                        end
                        
                    tj = threshold(tj, q_threshold_mvpa_reg_cov, 'fdr', 'k', k_threshold_mvpa_reg_cov); 
                    
                    datsig = tj.dat(logical(tj.sig));
                    datsigneg = datsig(datsig<0);
                    datsigpos = datsig(datsig>0);

                        if isempty(datsigneg) && ~isempty(datsigpos)

                            o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.9 .4 0], 'maxcolor', [1 1 0]);%, 'cmaprange', [min(datsigpos) max(datsigpos)]);

                        elseif isempty(datsigpos) && ~isempty(datsigneg)

                            o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'mincolor',[.1 .8 .8], 'maxcolor', [.1 .1 .8]);%, 'cmaprange', [min(datsigneg) max(datsigneg)]);

                        else

                            o2 = addblobs(o2, region(tj), 'wh_montages', (2*j)-1:2*j, 'splitcolor',{[.1 .8 .8] [.1 .1 .8] [.9 .4 0] [1 1 0]});%, 'cmaprange', [min(datsigneg) max(datsigneg) min(datsigpos) max(datsigpos)]);

                        end
                    
                    o2 = legend(o2);

                    o2 = title_montage(o2, 2*j, [analysisname ' FDR ' num2str(q_threshold_mvpa_reg_cov) ' ' names{j} ' ' mask_string ' ' scaling_string]);

                end % for loop over regressors

            figtitle = sprintf('%s_%s_%s_%1.4f_FDR_montage_%s_%s_%s', analysisname, results_suffix, algorithm_mvpa_reg_cov, q_threshold_mvpa_reg_cov, names_string, mask_string, scaling_string);
            set(gcf, 'Tag', figtitle); plugin_set_figure_size;
            drawnow, snapnow;

                if save_figures_glm
                    plugin_save_figure;
                end

            clear o2, clear figtitle, clear j, clear tj
        
        end % if loop exist cons2boot
        
    end % if loop bootstrap
   
end % for loop over contrasts/conditions


%% SAVE RESULTS
% -------------------------------------------------------------------------

fprintf('\n\n');
printhdr('APPENDING REGION OBJECTS TO SAVED RESULTS');
fprintf('\n\n');
    
    if ~dorobfit_parcelwise
        
        cd(resultsdir); % unannex image_names_and_setup.mat file if already datalad saved to prevent write permission problems
        ! git annex unannex regression_stats_and_maps*.mat
        cd(rootdir);
    
        savefilenamedata_region = fullfile(resultsdir, ['regression_stats_and_maps_', mygroupnamefield, '_', scaling_string, '_', results_suffix, '.mat']);
        save(savefilenamedata_region, 'region_objs_unc', 'region_objs_fdr', 'region_tables_unc', 'region_tables_fdr', 'region_tables_cov_unc', 'region_tables_cov_fdr', '-append');
        
        if has_bayes
            save(savefilenamedata_region, 'region_objs_Bayes', 'region_tables_Bayes', 'region_tables_cov_Bayes', '-append');
        end
        
        if has_tfce
            save(savefilenamedata_region, 'region_objs_tfce_unc', 'region_objs_tfce_corr', 'region_tables_tfce_unc', 'region_tables_tfce_corr', ...
                'region_tables_cov_tfce_unc','region_tables_cov_tfce_corr', ...
                'tfce_stat_imgs_thr_fdr', 'tfce_stat_imgs_thr_fwe', 'tfce_correction', '-append'); 
        end
        
    else
        
        cd(resultsdir); % unannex image_names_and_setup.mat file if already datalad saved to prevent write permission problems
        ! git annex unannex parcelwise_stats_and_maps*.mat
        cd(rootdir);
        
        savefilenamedata_region = fullfile(resultsdir, ['parcelwise_stats_and_maps_', mygroupnamefield, '_', scaling_string, '_', results_suffix, '.mat']);
        save(savefilenamedata_region, 'region_objs_unc', 'region_objs_fdr', 'region_tables_unc', 'region_tables_fdr', 'region_tables_cov_unc', 'region_tables_cov_fdr', '-append');
            
        if has_bayes
            save(savefilenamedata_region, 'region_objs_Bayes', 'region_tables_Bayes', 'region_tables_cov_Bayes', '-append');
        end
        
    end 
        
    fprintf('\nAdded region objects for %s\n', mygroupnamefield);

    fprintf('\nFilename: %s\n', savefilenamedata_region);
    

if dobootstrap_mvpa_reg_cov
    
    fprintf('\n\n');
    printhdr('APPENDING BOOTSTRAPPED MVPA RESULTS');
    fprintf('\n\n');
    
    savefilenamedata_mvpa = fullfile(resultsdir, ['mvpa_stats_and_maps_', mygroupnamefield, '_', scaling_string, '_', results_suffix, '.mat']);
    save(savefilenamedata_mvpa, 'mvpa_bs_stats_results','-append');
    fprintf('\nSaved mvpa_stats_results for %s\n', mygroupnamefield);

    fprintf('\nFilename: %s\n', savefilenamedata_mvpa);

end